server:
  port: 8189
  servlet:
    context-path: /timeline
spring:
  datasource:
    url: 'jdbc:mysql://localhost:3306/timeline'
    username: 'root'
    password: '>4A,/7Pu{fYf4+Q}'
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
  flyway:
    enabled: true
    validate-on-migrate: true


