# for MySQL
#server:
#  port: 8189
#  servlet:
#    context-path: /timeline
#spring:
#  datasource:
#    url: 'jdbc:mysql://localhost:3306/timeline'
#    username: 'root'
#    password: 'root'
#    driver-class-name: com.mysql.cj.jdbc.Driver
#  jpa:
#    show-sql: true
#    properties:
#      hibernate:
#        dialect: org.hibernate.dialect.MySQL8Dialect
#  flyway:
#    enabled: true
#    validate-on-migrate: true

server:
  port: 8189
  servlet:
    context-path: /timeline  # Контекстный путь сервлета

spring:
  datasource:
    url: jdbc:h2:mem:timeline;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE  # URL базы данных H2
    username: sa  # Пользователь базы данных H2
    password: password  # Пароль базы данных H2
    driver-class-name: org.h2.Driver  # Класс драйвера H2

  jpa:
    #show-sql: true  # Показывать SQL-запросы в логах
    show-sql: false  # Не показывать SQL-запросы в логах
    hibernate:
      ddl-auto: update  # Автоматическое обновление схемы базы данных
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect  # Диалект Hibernate для H2

  flyway:
    enabled: true  # Включить Flyway для миграций базы данных
    validate-on-migrate: true  # Проверять валидность схемы перед миграцией

